// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteResultRecord(arg1, arg2) {
  return window['go']['main']['App']['DeleteResultRecord'](arg1, arg2);
}

export function DeleteResults(arg1, arg2) {
  return window['go']['main']['App']['DeleteResults'](arg1, arg2);
}

export function DeleteScanRecord(arg1) {
  return window['go']['main']['App']['DeleteScanRecord'](arg1);
}

export function DiffScans(arg1, arg2) {
  return window['go']['main']['App']['DiffScans'](arg1, arg2);
}

export function GetDictWords(arg1) {
  return window['go']['main']['App']['GetDictWords'](arg1);
}

export function ListScans() {
  return window['go']['main']['App']['ListScans']();
}

export function LoadScanResults(arg1) {
  return window['go']['main']['App']['LoadScanResults'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickDict() {
  return window['go']['main']['App']['PickDict']();
}

export function RecheckBatch(arg1, arg2) {
  return window['go']['main']['App']['RecheckBatch'](arg1, arg2);
}

export function StartScan(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function UpdateReview(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateReview'](arg1, arg2, arg3, arg4);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
