// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteResultRecord(arg1:number,arg2:number):Promise<void>;

export function DeleteResults(arg1:number,arg2:Array<number>):Promise<void>;

export function DeleteScanRecord(arg1:number):Promise<void>;

export function DiffScans(arg1:number,arg2:number):Promise<model.DiffResult>;

export function GetDictWords(arg1:string):Promise<Array<string>>;

export function ListScans():Promise<Array<model.ScanSummary>>;

export function LoadScanResults(arg1:number):Promise<Array<model.ResultRow>>;

export function OpenURL(arg1:string):Promise<void>;

export function PickDict():Promise<string>;

export function RecheckBatch(arg1:number,arg2:Array<string>):Promise<Array<model.RecheckItem>>;

export function StartScan(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:string,arg7:string):Promise<void>;

export function StopScan():Promise<void>;

export function UpdateReview(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function Version():Promise<string>;
